# Generated by Django 3.1 on 2021-09-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210922_1810'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variations',
        ),
    ]
