# Generated by Django 3.1 on 2021-09-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210922_1810'),
        ('store', '0003_auto_20210922_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
